### ISSUE TITLE
Bug: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0') at TournamentBracketModal.render

### ISSUE THREAD

**Issue by gerry-mandering** [trancendering/Transcendence_Backend#31]
### Issue Type

- [x] Bug (오류)
- [ ] Feature Request (기능 요청)
- [ ] Performance (성능 문제)
- [ ] UI/Design (UI/디자인 관련)
- [ ] Documentation (문서 관련)
- [ ] Enhancement (개선 제안)
- [ ] Other - Please Describe:

### Priority

- [ ] Critical
- [ ] High
- [ ] Medium
- [ ] Low

### Summary
- Bug: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0') at TournamentBracketModal.render

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at TournamentBracketModal.render (tournamentBracketModal.js:37:64)
    at Game.renderAll (component.js:20:31)
    at router (router.js:53:31)
    at navigateTo (router.js:29:2)
    at singleGameActionHandler.startGame (singleGameActionHandler.js:63:69)
    at Socket.eval (gameActionHandler.js:76:9)
    at Emitter.emit (index.mjs:140:20)
    at Socket.emitEvent (socket.js:505:20)
    at eval (socket.js:565:51)
    at Array.forEach (<anonymous>)
```

### Steps to Reproduce

1. JS 로딩 이후 토너먼트를 시작하지 않고 싱글 모드를 시작 후 반복
2.
3.

### Environment

- Operating System:
- Browser (if applicable):
- Version:

**Comment by gerry-mandering** [comment]
Thank you hyeyukim
